# Experiment 1: Data Wrangling I

In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/trushantramdasjadhav/Desktop/system/1-DW-I/StudentsPerformance.csv")

In [4]:
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72            NaN
1                 completed          69             90           88.0
2                      none          90             95           93.0
3                      none          47             57           44.0
4                      none          76             78           75.0
..                      ...         ...            ...            ...
995               completed          88             99           95.0
996                    none          62             55           55.0
997               completed          59             71           65.0
998               completed          68             78           77.0
999                    none          77             86           86.0

[1000 rows x 8 columns]

# find Missing Values

In [5]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  1
dtype: int64

# remove columns that contain missing (NaN) values from a Pandas DataFrame.

In [20]:
# axis=1

#Specifies columns.

#axis=0 → rows

#axis=1 → columns

In [8]:
df.dropna(axis=1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score
0,female,group B,bachelor's degree,standard,none,72,72
1,female,group C,some college,standard,completed,69,90
2,female,group B,master's degree,standard,none,90,95
3,male,group A,associate's degree,free/reduced,none,47,57
4,male,group C,some college,standard,none,76,78
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99
996,male,group C,high school,free/reduced,none,62,55
997,female,group C,high school,free/reduced,completed,59,71
998,female,group D,some college,standard,completed,68,78
999,female,group D,some college,free/reduced,none,77,86

# Describe Method to get Initial Statistics

In [22]:
print(df.describe())

       math score  reading score  writing score
count  1000.00000    1000.000000     999.000000
mean     66.08900      69.169000      68.048048
std      15.16308      14.600192      15.202102
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.500000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Data Formating:  Display Data types if not in proper format apply proper conversion method

In [23]:
df.dtypes

gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                       int64
reading score                    int64
writing score                  float64
dtype: object

# integer-location based indexing  (select specific columns from a DataFrame using index positions)

In [24]:
y = df.iloc[:, 0:2]
print(y)

     gender race/ethnicity
0    female        group B
1    female        group C
2    female        group B
3      male        group A
4      male        group C
..      ...            ...
995  female        group E
996    male        group C
997  female        group C
998  female        group D
999  female        group D

[1000 rows x 2 columns]

# Turn Categorical Variable into Numerical

In [9]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/trushantramdasjadhav/Desktop/system/venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sklearn.preprocessing import LabelEncoder
y = ['male', 'female']
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0]

In [28]:
#Count how many times each unique value appears in the column race/ethnicity of a Pandas DataFrame.

In [11]:
print(df['race/ethnicity'].value_counts())

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [20]:
# convert a categorical column (lunch) into numerical form using One-Hot Encoding and then add it back to the original DataFrame.
# pd.get_dummies() performs One-Hot Encoding.
# It converts each unique category in the lunch column into a separate binary (0/1) column.

In [41]:
df_Lunch = pd.get_dummies(df['lunch'])
df_new = pd.concat([df, df_Lunch], axis=1)#pd.concat() joins DataFrames together.axis=1 means join column-wise.
#This adds the new one-hot encoded columns to the original DataFrame.
df_new #for print

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,free/reduced,standard
0,female,group B,bachelor's degree,standard,none,72,72,NaN,False,True
1,female,group C,some college,standard,completed,69,90,88.0,False,True
2,female,group B,master's degree,standard,none,90,95,93.0,False,True
3,male,group A,associate's degree,free/reduced,none,47,57,44.0,True,False
4,male,group C,some college,standard,none,76,78,75.0,False,True
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95.0,False,True
996,male,group C,high school,free/reduced,none,62,55,55.0,True,False
997,female,group C,high school,free/reduced,completed,59,71,65.0,True,False
998,female,group D,some college,standard,completed,68,78,77.0,False,True
999,female,group D,some college,free/reduced,none,77,86,86.0,True,False

In [31]:
from sklearn.preprocessing import LabelEncoder

y = ['Yes', 'No', 'Yes', 'No']   # define y first

le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[1 0 1 0]

In [23]:
#LabelEncoder converts labels (categories) into numeric values.

In [32]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("StudentsPerformance.csv")

y = df['gender']   # column name containing labels

le = LabelEncoder()
y = le.fit_transform(y) #fit(): finds unique classes in y transform(): assigns numbers to each class.


print(y)

[0 0 0 1 1 0 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1 1 0
 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 0 1 0 1
 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0
 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1
 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1
 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1
 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0
 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1
 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0
 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 0 1
 0 0 1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0
 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1
 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0
 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 1 1 0 1 1
 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1
 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1
 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1
 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1
 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1
 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0
 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0
 0]

In [12]:
df.head() # Top 5 entries of the table

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,NaN
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0